language: ruby
rvm:
  - 2.1
script:
  - mdl -r MD003,MD004,MD005,MD006,MD007,MD008,MD010,MD011,MD012,MD014,MD018,MD019,MD020,MD021,MD023,MD024,MD025,MD026,MD027,MD028,MD029,MD030,MD032 _posts/
  - sass-convert --from scss --to scss --in-place --recursive _sass
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx
  - scss-lint -c ._scss-lint.yml
before_install:
  - gem install mdl
  - gem install scss-lint
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
